import importedData from './imports';

export const categories = ['Духовые инструменты',
  'Небольшие духовые инструменты',
  'Категория №3',
  'Категория №4',
  'Категория №5',
  'Категория №6',
];

export const data = [
  {
    name: 'Саксофон',
    translate: 'Saxophone',
    image: importedData.saxophoneImg,
    audio: importedData.saxophoneAudio,
    text: 'Тростевой духовой музыкальный инструмент, по принципу звукоизвлечения принадлежащий к семейству язычковых деревянных духовых музыкальных инструментов. Инструмент обладает полным и мощным звучанием, певучим тембром и большой технической подвижностью.',
  },
  {
    name: 'Волынка',
    translate: 'Bagpipes',
    image: importedData.bagpipesImg,
    audio: importedData.bagpipesAudio,
    text: 'Традиционный музыкальный духовой язычковый инструмент многих народов Европы. Волынка один из древнейших музыкальных инструментов, известных человечеству. Её история насчитывает не одно тысячелетие. Причиной этому — её незамысловатое и доступное устройство.',
  },
  {
    name: 'Туба',
    translate: 'Tuba',
    image: importedData.tubaImg,
    audio: importedData.tubaAudio,
    text: 'Широкомензурный медный духовой музыкальный инструмент, самый низкий по регистру. Используется в основном в симфоническом и духовом оркестрах, где ей принадлежит роль басового инструмента в группе медных духовых. Все чаще используется в джазовой, а также камерной музыке.',
  },
  {
    name: 'Орган',
    translate: 'Organ',
    image: importedData.organImg,
    audio: importedData.organAudio,
    text: 'Клавишный духовой музыкальный инструмент. Большие концертные органы превосходят по габаритам все прочие музыкальные инструменты. Используется в богослужениях католиков и протестантов как аккомпанирующий и (реже) сольный инструмент.',
  },
  {
    name: 'Труба',
    translate: 'Trumpet',
    image: importedData.trumpetImg,
    audio: importedData.trumpetAudio,
    text: 'Медный духовой музыкальный инструмент альтово-сопранового регистра, самый высокий по звучанию среди медных духовых. Обладает ярким, блестящим тембром, используется как сольный инструмент или в симфоническом и духовом оркестрах, а также в джазе и других жанрах.',
  },
  {
    name: 'Аккордеон',
    translate: 'Accordion',
    image: importedData.accordionImg,
    audio: importedData.accordionAudio,
    text: 'Хроматическая ручная гармоника с клавиатурой мелодии фортепианного (наиболее часто) типа. Клавиатура аккомпанемента такая же как у баяна: с 5—6 рядами кнопок, звучащими басами и аккордами (готовый аккордеон) или отдельными нотами (выборный или готово-выборный аккордеон).',
  },
  {
    name: 'Флейта',
    translate: 'Flute',
    image: importedData.fluteImg,
    audio: importedData.fluteAudio,
    text: 'Лабиальный духовой музыкальный инструмент, в котором первичным источником колебаний является воздушная струя, рассекающаяся о край стенки инструмента. Относится к группе деревянных духовых.',
  },
  {
    name: 'Кларнет',
    translate: 'Clarinet',
    image: importedData.clarinetImg,
    audio: importedData.clarinetAudio,
    text: 'Язычковый деревянный духовой музыкальный инструмент с одинарной тростью. Применяется в самых разнообразных музыкальных жанрах и составах: в качестве сольного инструмента, в камерных ансамблях, симфонических и духовых оркестрах, народной музыке, на эстраде и в джазе.',
  },
  {
    name: 'Казу',
    translate: 'Kazoo',
    image: importedData.kazooImg,
    audio: importedData.kazooAudio,
    text: 'Американский народный музыкальный инструмент, применяемый в музыке стиля скиффл. Казу представляет собой небольшой металлический, пластмассовый или деревянный цилиндр, сужающийся к концу. В середину цилиндра сверху вставлена металлическая пробка с мембраной из папиросной бумаги. Чтобы исполнять музыку на казу, нужно в него петь, при этом бумажная мембрана значительно изменяет голос.',
  },
  {
    name: 'Пан-флейта',
    translate: 'Panflute',
    image: importedData.panfluteImg,
    audio: importedData.panfluteAudio,
    text: 'Флейтовый музыкальный инструмент, состоящий из нескольких соединённых или отдельных трубок как правило без пальцевых отверстий. Нижние концы трубок могут быть открытыми или закрытыми.',
  },
  {
    name: 'Горн',
    translate: 'Horn',
    image: importedData.hornImg,
    audio: importedData.hornAudio,
    text: 'Сигнальный музыкальный инструмент, родоначальник всех медных духовых инструментов. Горн напоминает трубу, но в нём отсутствует вентильный механизм, отчего его исполнительные возможности резко ограничены: горн может воспроизводить ноты только в пределах натурального звукоряда.',
  },
  {
    name: 'Губная гармошка',
    translate: 'Harmonica',
    image: importedData.harmonicaImg,
    audio: importedData.harmonicaAudio,
    text: 'Музыкальный инструмент семейства гармоник. Представляет собой небольшой брусок со множеством отверстий сбоку. Выбор извлекаемых звуков осуществляется положением губ и языка на отверстиях, а также направлением движения воздуха на вдох или выдох.',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },
  {
    name: '',
    translate: '',
    image: '',
    audio: '',
    text: '',
  },

];
